### ISSUE TITLE
chrome branch fails on windows

### ISSUE THREAD

**Issue by paloblanco** [mikepqr/resume.md#14]
The python script is able to detect my chrome install, but fails at making the pdf. This fails regardless of whether or not the pdf already exists:

```
Wrote resume.html
Found Chrome or Chromium at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
[0419/104241.939:ERROR:headless_shell.cc(595)] Writing to file resume.pdf was unsuccessful, could not open file: FILE_ERROR_ACCESS_DENIED
```

The program hangs at this point, and I need to interrupt it to gain control again.

**Comment by amandal1810** [comment]
A detailed discussion on #13

**Comment by Neurrone** [comment]
I'm seeing this as well on Windows.

**Comment by mikepqr** [comment]
I believe #19 fixes this. Please let me know if not. (And thanks to @amandal1810 for the clue. I will try to find time to take a look at the rest of your PR asap.)
