### ISSUE TITLE
[Feature Request] Hot reload on file change (.md/.css)

### ISSUE THREAD

**Issue by amandal1810** [mikepqr/resume.md#17]
[Feature Request]

Use case: when writing my resume, I want to make sure that my PDF output does not exceed one page. Currently, I have to update the .md or .css file and run the command every time and check the PDF output. A better UX would be to have a watcher that would run the .py script every time the .md or .css file changes.
It would be great if we did not have to run the command again and again when updating my resume.

I will get my hands dirty on this, next weekend. However, I can test this only on win32 and I will need support for testing on macOS and Linux.

**Comment by mikepqr** [comment]
I want to avoid solving problems three times for three platforms (complexity, maintenance overhead) and adding dependencies for users (made that mistake before with weasyprint). Watching the filesystem is not possible in a cross-platform way without adding dependencies. I've therefore previously decided that a watcher is out of scope for this project.

I personally handle it using `entr` on Linux, i.e. `ls git-files | entr python resume.py`. It's a single command. I assume something similar is possible on Windows. If you come up with a nice Windows solution we could put it in the README if it's non-obvious.

**Comment by mikepqr** [comment]
Note: if you can figure out how to do this in a cross-platform way without adding dependencies, there's no doubt it's a useful workflow, and I'll take a PR for that.

**Comment by rifazn** [comment]
IMO, this should be handled by the user's development environment. In _vim_, this can be easily done my running `make` every time a file in the project is saved. Something like the following in command mode should do the trick:

```
set makeprg=python3\ resume.py
autocmd BufWritePost * :make
```

I believe similar solutions exist for all major text editors/IDEs. A search for in case of VSCode has taken me to: https://stackoverflow.com/questions/68059778/auto-run-command-from-vscode-extension-on-file-save

**Comment by mikepqr** [comment]
I reopend this, but on reflection it is definitely out of scope.
