### ISSUE TITLE
Add table support

### ISSUE THREAD

**Issue by benjaminmaccini** [mikepqr/resume.md#2]
## Description

Render markdown tables. Should be able to add something along these lines and have it render.

```
| asdf | fdas |
| --- | --- |
| 123 | 321 |
```

Could be nice to have some nice CSS for the tables too.

## Minimal Fix 
Change

`python -m markdown -x smarty resume.md >> $@`

to

`python -m markdown -x smarty -x tables resume.md >> $@`

[Reference](https://python-markdown.github.io/extensions/)

**Comment by williamsmj** [comment]
Thanks for the suggestion! That change is of course easy to make, but I'm wondering what the use case is? Unless you're (mis?)using tables for layout (in which case markdown is the wrong thing altogether), I don't see a reason to include a table in a standard resume.

And with that in mind it's difficult to know what kind of default CSS to provide. Could you give some examples of resumes with tables, or at least what you'd do with tables if you could use them?

**Comment by benjaminmaccini** [comment]
I used it for layout, specifically displaying denser sections (e.g. skills or proficiency of languages and corresponding packages). In your opinion, what would be the right way to manage layout? HTML? Also, good point, I can't find any example resumes with a table... should probably change mine then lol 🤔. 

Feel free to close out the issue, I don't believe it's broadly applicable.

**Comment by mikepqr** [comment]
In general one should manage layout of HTML with CSS, not with tables.

In this particular case, if you have a list of skills then it should be a bulleted list in the markdown and then style the corresponding `ul` and `li` elements in CSS to make it the list more compact, make the items span-level, etc., etc.

The challenge with resume.md is you don't have much control over the HTML (you can't even apply classes), so it's tricky to do anything too clever with CSS. But having seen a lot of clever resumes, I think that's a feature not a bug! :-)
