### ISSUE TITLE
Why markdown over json?

### ISSUE THREAD

**Issue by 9s-l-s9** [mikepqr/resume.md#24]
Hey,

really cool project. I especially like your simple and clean design.  I am in the process of switching from MSWord to something closer to raw text and was wondering what your reasons are for using markdown instead of json... especially because you know about jsonresume, which I just found out about because of your project.  

So... why? :D

**Comment by mikepqr** [comment]
For the same reason GitHub doesn't ask you to write your comments in JSON: because the writer is a human not a computer.
