### ISSUE TITLE
Having an empty line before the first `#` gives an IndexError

### ISSUE THREAD

**Issue by rifazn** [mikepqr/resume.md#25]
In the function:

```python
def title(md: str) -> str:
    for line in md.splitlines():
        if line[0] == "#":  # IndexError if line is empty
            return line.strip("#").strip()
    raise ValueError("Cannot find any lines that look like markdown headings")
```

If there is an empty line in `md`, that line is just an empty string in the list returned by `md.splitlines()`. Accessing the empty string gives the `IndexError`.

Checking truthfulness on the `line` before accessing `line[0]` should be enough:

```python
        if line and line[0] == "#":  # Check that line is truthy first
```

May I do a Pull Request if the issue and the resolution proposed is satisfactory?

**Comment by mikepqr** [comment]
Good catch. Your fix looks good. PR welcome!
