### ISSUE TITLE
[Help] Date right aligned when using bullet points

### ISSUE THREAD

**Issue by bambirombi** [mikepqr/resume.md#39]
I want to be able to align the date to the right when I am using a bulleted list. 

I have this: 

**Formación Complementaria**

- **Título de socorrismo y priemeros auxilios, Cruz Roja** [40h] <span>2022<span>

The problem is that the 2022 is not right aligned in the pdf nor the html.

I want the same output that generates this: 

### <span>Título de socorrismo y priemeros auxilios, Cruz Roja</span> <span>2022</span>

But preceded with a bullet point.

**Comment by mikepqr** [comment]
I have not tested this, but try something like this in the css

```
li {
    margin-left: 0;
    margin-right: 0;
    justify-content: space-between;
}
```

and then

```
- <span>Título de socorrismo y priemeros auxilios, Cruz Roja [40h]</span> <span>2022</span>
```

If that doesn't work or you need further help I suggest to try a general HTML/CSS help site (this is a HTML/CSS problem, not a resume.md problem).
