### ISSUE TITLE
Headers & Footers on latest Chrome

### ISSUE THREAD

**Issue by ataylor-us** [mikepqr/resume.md#41]
Hey, apologies for the brief issue report.  I'm using this to help with a school assignment and have to get back to writing it.

I tried with the latest Google Chrome on macOS (`120.0.6099.62`, installed with brew) , and with the Chromium that ships with the latest Debian stable (`120.0.6099.71`, tried via a Docker container), and it seems to print headers and footers on the output pdf.

I'm able to generate the expected pdf by pulling in a earlier debian container (buster) that ships with version 90 or so of Chromium, and I'm able to generate a correct pdf with that.  I'm assuming it worked with 119, and broke with 120.

Thanks for this wonderful project!  Let me know if I can help at all.

**Comment by mikepqr** [comment]
Ah. Thanks for the report! Looks like they renamed the option.

Can you try changing the string on line 30 of resume.py to `--no-pdf-header-footer`?

If you can't figure out how to do that, or that doesn't work, let me know and I'll take a closer look.

**Comment by mikepqr** [comment]
Nice. Can you add the comment I suggest, and then we can push this in.
