### ISSUE TITLE
Warnings about box-shadow and media type

### ISSUE THREAD

**Issue by eatmoresushi** [mikepqr/resume.md#6]
Hi thanks for the awesome project.

I got the following warnings after running `make resume`

```
WARNING: Ignored `box-shadow: 2px 2px 4px #AAAAAA` at 14:5, unknown property.
WARNING: Ignored `box-shadow: none` at 79:9, unknown property.
WARNING: Expected a media type, got screen/**/and/**/(max-width: 800px)
WARNING: Invalid media type " screen and (max-width: 800px) " the whole @media rule was ignored at 95:1.
```

Looks like *weasyprint* does not support *box-shadow*.

**Comment by mikepqr** [comment]
Right. These warnings are harmless, but it would be good to get rid of them. That may be possible by reorganizing the CSS so weasyprint. I'm reluctant to suppress all warnings though.

I'll leave this open in case anyone can fix the warnings, but I won't be spending time on it myself. In the long run, I would prefer to eliminate the weasyprint dependency altogether and switch to headless Chrome or a similar tool. For better or worse, this is easier to install for most users.
